# Generated by Django 4.2.11 on 2026-04-27 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_first_name_customer_first_name_and_more'),
    ]

    operations = [
        migrations.RunSQL("""
            INSERT INTO store_collection (title)
            VALUES ('collection1')
        """, """
            DELETE FROM store_collection 
            WHERE title = 'collection1'
        """)
    ]
